/**
 * bugTrackerService.js
 * B.L.A.S.T. — Bug Tracker Integration
 * Supported: Jira Cloud · YouTrack · Linear · GitHub Issues
 */

export const BT_TOOLS = {
  jira: {
    id: 'jira',
    name: 'Jira',
    icon: '🎯',
    color: '#0052cc',
    fields: [
      { key: 'baseUrl',    label: 'Jira Base URL',  placeholder: 'https://yourorg.atlassian.net', type: 'url',      hint: 'Your Atlassian domain' },
      { key: 'email',      label: 'Email',           placeholder: 'you@company.com',               type: 'email',    hint: 'Atlassian account email' },
      { key: 'apiToken',   label: 'API Token',       placeholder: 'Paste Atlassian API token',     type: 'password', hint: 'Create at id.atlassian.com/manage-profile/security/api-tokens' },
      { key: 'projectKey', label: 'Project Key',     placeholder: 'e.g., PROJ',                   type: 'text',     hint: 'e.g., QA, BUG, PROJ' },
    ],
  },
  youtrack: {
    id: 'youtrack',
    name: 'YouTrack',
    icon: '🔷',
    color: '#007ECC',
    fields: [
      { key: 'baseUrl',   label: 'YouTrack URL',       placeholder: 'https://yourorg.youtrack.cloud', type: 'url',      hint: 'Your YouTrack instance URL' },
      { key: 'token',     label: 'Permanent Token',    placeholder: 'Paste your token',              type: 'password', hint: 'Profile > Account Security > Tokens' },
      { key: 'projectId', label: 'Project Short Name', placeholder: 'e.g., MYAPP',                  type: 'text',     hint: 'Short name shown in issue IDs' },
    ],
  },
  linear: {
    id: 'linear',
    name: 'Linear',
    icon: '📐',
    color: '#5E6AD2',
    fields: [
      { key: 'apiKey', label: 'API Key',  placeholder: 'lin_api_...',        type: 'password', hint: 'Settings > API > Personal API keys' },
      { key: 'teamId', label: 'Team ID',  placeholder: 'Paste Linear Team ID', type: 'text',     hint: 'Settings > Teams > (your team) > copy ID' },
    ],
  },
  github: {
    id: 'github',
    name: 'GitHub Issues',
    icon: '🐙',
    color: '#24292F',
    fields: [
      { key: 'token', label: 'Personal Access Token', placeholder: 'ghp_...',            type: 'password', hint: 'github.com Settings > Developer settings > Personal access tokens' },
      { key: 'owner', label: 'Repo Owner',            placeholder: 'e.g., your-org',     type: 'text',     hint: 'Organisation or username' },
      { key: 'repo',  label: 'Repository',            placeholder: 'e.g., my-project',   type: 'text',     hint: 'Repository name (without owner)' },
    ],
  },
};

const SEV_TO_JIRA_PRI = { Critical: 'Blocker', High: 'Critical', Medium: 'Major', Low: 'Minor' };
const PRI_TO_LINEAR   = { P0: 1, P1: 2, P2: 3, P3: 4 };
// eslint-disable-next-line no-unused-vars
const SEV_TO_ADO      = { Critical: '1 - Critical', High: '2 - High', Medium: '3 - Medium', Low: '4 - Low' };

/* ── Description builders ──────────────────────────────────────── */
function buildPlainDesc(t) {
  let d = `ACTUAL BEHAVIOUR:\n${t.objectives?.actualBehaviour || 'N/A'}\n\n`;
  d += `EXPECTED BEHAVIOUR:\n${t.objectives?.expectedBehaviour || 'N/A'}\n\n`;
  d += `STEPS TO REPRODUCE:\n${(t.criteria?.stepsToReproduce || []).map((s, i) => `${i + 1}. ${s}`).join('\n')}\n\n`;
  d += `ENVIRONMENT:\nBrowser: ${t.environment?.browser || 'N/A'} | OS: ${t.environment?.operatingSystem || 'N/A'} | Role: ${t.environment?.userRole || 'N/A'} | Env: ${t.environment?.testEnvironment || 'N/A'}\n\n`;
  d += `ROOT CAUSE (${t.rootCause?.probableLayer || 'TBD'}):\n${t.rootCause?.summary || 'TBD'}\n\n`;
  d += `ACCEPTANCE CRITERIA:\n${(t.criteria?.fixAcceptanceCriteria || []).map(ac => `- ${ac}`).join('\n')}\n\n`;
  d += `Severity: ${t.severity} | Priority: ${t.priority} | Effort: ${t.additionalDetails?.estimatedFixEffort || 'M'}\n`;
  d += `\n*Generated by B.L.A.S.T. Defect Radar — RICE-POT Framework*`;
  return d;
}

function buildMarkdownDesc(t) {
  let d = `## ${t.objectives?.delta || t.title}\n\n`;
  d += `**Severity:** ${t.severity} | **Priority:** ${t.priority} | **Effort:** ${t.additionalDetails?.estimatedFixEffort || 'M'}\n\n`;
  d += `### Actual Behaviour\n${t.objectives?.actualBehaviour || 'N/A'}\n\n`;
  d += `### Expected Behaviour\n${t.objectives?.expectedBehaviour || 'N/A'}\n\n`;
  d += `### Steps to Reproduce\n`;
  d += (t.criteria?.stepsToReproduce || []).map((s, i) => `${i + 1}. ${s}`).join('\n') + '\n\n';
  d += `### Environment\n`;
  d += `| Field | Value |\n|---|---|\n`;
  d += `| Browser | ${t.environment?.browser || 'N/A'} |\n`;
  d += `| OS | ${t.environment?.operatingSystem || 'N/A'} |\n`;
  d += `| Role | ${t.environment?.userRole || 'N/A'} |\n`;
  d += `| Test Env | ${t.environment?.testEnvironment || 'N/A'} |\n\n`;
  d += `### Root Cause\n**Layer:** \`${t.rootCause?.probableLayer || 'TBD'}\`\n\n${t.rootCause?.summary || 'TBD'}\n\n`;
  d += `### Acceptance Criteria\n${(t.criteria?.fixAcceptanceCriteria || []).map(ac => `- [ ] ${ac}`).join('\n')}\n\n`;
  d += `---\n*Generated by [B.L.A.S.T. Defect Radar](https://github.com) — RICE-POT Framework*`;
  return d;
}

class BugTrackerService {

  /* ── Jira Cloud ──────────────────────────────────────────────── */
  async pushToJira(ticket, cfg) {
    const auth = btoa(`${cfg.email}:${cfg.apiToken}`);
    const base = cfg.baseUrl.replace(/\/$/, '');

    const payload = {
      fields: {
        project:     { key: cfg.projectKey },
        summary:     ticket.title,
        description: {
          type: 'doc', version: 1,
          content: [{
            type: 'paragraph',
            content: [{ type: 'text', text: buildPlainDesc(ticket) }],
          }],
        },
        issuetype: { name: ticket.jiraFields?.issueType || 'Bug' },
        priority:  { name: SEV_TO_JIRA_PRI[ticket.severity] || ticket.jiraFields?.priority || 'Major' },
        labels:    (ticket.jiraFields?.labels || []).filter(l => /^[a-zA-Z0-9_-]+$/.test(l)),
      },
    };

    const res = await fetch(`${base}/rest/api/3/issue`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${auth}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.errorMessages?.[0] || Object.values(err.errors || {})[0] || `HTTP ${res.status}`;
      if (res.status === 401) throw new Error('Invalid credentials — check email and API token');
      if (res.status === 403) throw new Error('Forbidden — check project permissions and CORS settings for Jira Cloud');
      throw new Error(msg);
    }

    const data = await res.json();
    return { id: data.key, url: `${base}/browse/${data.key}` };
  }

  /* ── YouTrack ────────────────────────────────────────────────── */
  async pushToYouTrack(ticket, cfg) {
    const base = cfg.baseUrl.replace(/\/$/, '');

    const res = await fetch(`${base}/api/issues?fields=id,idReadable`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${cfg.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        project:     { id: cfg.projectId },
        summary:     ticket.title,
        description: buildMarkdownDesc(ticket),
      }),
    });

    if (!res.ok) {
      if (res.status === 401) throw new Error('Invalid token — check your YouTrack permanent token');
      if (res.status === 404) throw new Error(`Project "${cfg.projectId}" not found`);
      throw new Error(`YouTrack HTTP ${res.status}`);
    }

    const data = await res.json();
    return { id: data.idReadable, url: `${base}/issue/${data.idReadable}` };
  }

  /* ── Linear ──────────────────────────────────────────────────── */
  async pushToLinear(ticket, cfg) {
    const res = await fetch('https://api.linear.app/graphql', {
      method: 'POST',
      headers: {
        Authorization: cfg.apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query: `
          mutation($input: IssueCreateInput!) {
            issueCreate(input: $input) {
              success
              issue { id identifier url title }
            }
          }
        `,
        variables: {
          input: {
            teamId:      cfg.teamId,
            title:       ticket.title,
            description: buildMarkdownDesc(ticket),
            priority:    PRI_TO_LINEAR[ticket.priority] || 3,
          },
        },
      }),
    });

    const data = await res.json();

    if (data.errors?.length) throw new Error(data.errors[0].message);
    if (!data.data?.issueCreate?.success) throw new Error('Linear issue creation failed');

    const issue = data.data.issueCreate.issue;
    return { id: issue.identifier, url: issue.url };
  }

  /* ── GitHub Issues ───────────────────────────────────────────── */
  async pushToGitHub(ticket, cfg) {
    const res = await fetch(`https://api.github.com/repos/${cfg.owner}/${cfg.repo}/issues`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${cfg.token}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github.v3+json',
      },
      body: JSON.stringify({
        title:  ticket.title,
        body:   buildMarkdownDesc(ticket),
        labels: (ticket.jiraFields?.labels || ['bug', 'ai-detected']).slice(0, 5),
      }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      if (res.status === 401) throw new Error('Invalid GitHub token — check Personal Access Token permissions');
      if (res.status === 404) throw new Error(`Repo ${cfg.owner}/${cfg.repo} not found or token lacks issues:write scope`);
      throw new Error(err.message || `GitHub HTTP ${res.status}`);
    }

    const data = await res.json();
    return { id: `#${data.number}`, url: data.html_url };
  }

  /* ── Dispatch ────────────────────────────────────────────────── */
  async push(toolId, ticket, cfg) {
    switch (toolId) {
      case 'jira':     return this.pushToJira(ticket, cfg);
      case 'youtrack': return this.pushToYouTrack(ticket, cfg);
      case 'linear':   return this.pushToLinear(ticket, cfg);
      case 'github':   return this.pushToGitHub(ticket, cfg);
      default:         throw new Error(`Unknown tracker: ${toolId}`);
    }
  }
}

export const bugTrackerService = new BugTrackerService();

/* ── localStorage helpers ────────────────────────────────────── */
const LS_KEY = 'blast_bt_config';

export function loadBtConfig() {
  try { return JSON.parse(localStorage.getItem(LS_KEY) || '{}'); }
  catch { return {}; }
}

export function saveBtConfig(cfg) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(cfg)); } catch {}
}
