// Layer 3: Export Utilities
// File: src/services/exportUtils.js

/**
 * Export Utilities
 * Handles markdown and PDF export formats
 */

class ExportUtils {
  /**
   * Generate Markdown from test plan
   */
  static generateMarkdown(testPlan, issueData) {
    const sections = [
      `# Test Plan: ${testPlan.issueKey}`,
      '',
      '## Issue Summary',
      `**Key:** ${testPlan.issueKey}`,
      `**Summary:** ${issueData.summary}`,
      `**Type:** ${issueData.type}`,
      `**Priority:** ${issueData.priority}`,
      `**Status:** ${issueData.status}`,
      '',
      '## Overview',
      `- **Total Test Cases:** ${this.countTestCases(testPlan)}`,
      `- **Generated At:** ${testPlan.generatedAt}`,
      `- **Generated By:** GROQ (openai/gpt-oss-120b)`,
      '',
      '---',
      '',
    ];

    // Add each section
    const sectionOrder = [
      { key: 'positiveScenarios', title: 'Positive Scenarios' },
      { key: 'negativeScenarios', title: 'Negative Scenarios' },
      { key: 'edgeCases', title: 'Edge Cases' },
      { key: 'securityTests', title: 'Security Tests' },
      { key: 'performanceTests', title: 'Performance Tests' },
    ];

    for (const section of sectionOrder) {
      sections.push(`## ${section.title}`);
      sections.push('');

      const testCases = testPlan.testPlan[section.key] || [];
      
      for (const testCase of testCases) {
        sections.push(`### ${testCase.id}: ${testCase.title}`);
        sections.push('');
        sections.push(`**Description:** ${testCase.description}`);
        sections.push('');

        if (testCase.steps && Array.isArray(testCase.steps)) {
          sections.push('**Steps:**');
          for (let i = 0; i < testCase.steps.length; i++) {
            sections.push(`${i + 1}. ${testCase.steps[i]}`);
          }
          sections.push('');
        }

        sections.push(`**Expected Result:** ${testCase.expectedResult}`);
        
        if (testCase.priority) {
          sections.push(`**Priority:** ${testCase.priority}`);
        }

        sections.push('');
        sections.push('---');
        sections.push('');
      }
    }

    // Add metadata
    if (testPlan.metadata) {
      sections.push('## Metadata');
      sections.push('');
      
      if (testPlan.metadata.totalTestCases) {
        sections.push(`**Total Test Cases:** ${testPlan.metadata.totalTestCases}`);
      }
      
      if (testPlan.metadata.riskAreas && testPlan.metadata.riskAreas.length > 0) {
        sections.push('**High-Risk Areas:**');
        for (const area of testPlan.metadata.riskAreas) {
          sections.push(`- ${area}`);
        }
        sections.push('');
      }

      if (testPlan.metadata.assumptions && testPlan.metadata.assumptions.length > 0) {
        sections.push('**Assumptions:**');
        for (const assumption of testPlan.metadata.assumptions) {
          sections.push(`- ${assumption}`);
        }
        sections.push('');
      }
    }

    return sections.join('\n');
  }

  /**
   * Generate HTML for PDF export
   */
  static generateHtml(testPlan, issueData) {
    const testCasesHtml = this.generateTestCasesHtml(testPlan);
    const metadataHtml = this.generateMetadataHtml(testPlan);

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      margin: 20px;
      background-color: #f9f9f9;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background-color: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
      margin-top: 0;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
      border-left: 4px solid #3498db;
      padding-left: 10px;
    }
    h3 {
      color: #7f8c8d;
      margin-top: 20px;
    }
    .header-section {
      background-color: #ecf0f1;
      padding: 15px;
      border-radius: 4px;
      margin-bottom: 20px;
    }
    .header-item {
      margin: 8px 0;
      display: flex;
      justify-content: space-between;
    }
    .header-label {
      font-weight: bold;
      color: #2c3e50;
    }
    .test-case {
      border: 1px solid #bdc3c7;
      padding: 15px;
      margin-bottom: 15px;
      border-radius: 4px;
      background-color: #f8f9fa;
    }
    .test-case-header {
      font-weight: bold;
      color: #2c3e50;
      margin-bottom: 10px;
      font-size: 16px;
    }
    .test-case-field {
      margin: 8px 0;
      padding: 8px;
      background-color: white;
      border-left: 3px solid #3498db;
      padding-left: 12px;
    }
    .test-case-label {
      font-weight: bold;
      color: #34495e;
      display: inline-block;
      min-width: 100px;
    }
    .priority {
      display: inline-block;
      padding: 3px 8px;
      border-radius: 3px;
      font-weight: bold;
      font-size: 12px;
    }
    .priority-high {
      background-color: #e74c3c;
      color: white;
    }
    .priority-medium {
      background-color: #f39c12;
      color: white;
    }
    .priority-low {
      background-color: #27ae60;
      color: white;
    }
    .steps-list {
      list-style-type: decimal;
      margin-left: 20px;
    }
    .steps-list li {
      margin: 5px 0;
    }
    .overview {
      background-color: #ecf0f1;
      padding: 15px;
      border-radius: 4px;
      margin-bottom: 20px;
    }
    .section-summary {
      display: inline-block;
      margin-right: 20px;
      padding: 10px;
      background-color: white;
      border-radius: 4px;
      margin-bottom: 5px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #bdc3c7;
      color: #7f8c8d;
      font-size: 12px;
    }
    .page-break {
      page-break-after: always;
    }
    @media print {
      body {
        margin: 0;
        background-color: white;
      }
      .container {
        box-shadow: none;
        max-width: 100%;
        margin: 0;
        padding: 0;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Test Plan Report: ${testPlan.issueKey}</h1>
    
    <div class="header-section">
      <div class="header-item">
        <span class="header-label">Issue Key:</span>
        <span>${testPlan.issueKey}</span>
      </div>
      <div class="header-item">
        <span class="header-label">Summary:</span>
        <span>${issueData.summary}</span>
      </div>
      <div class="header-item">
        <span class="header-label">Type:</span>
        <span>${issueData.type}</span>
      </div>
      <div class="header-item">
        <span class="header-label">Priority:</span>
        <span>${issueData.priority}</span>
      </div>
      <div class="header-item">
        <span class="header-label">Status:</span>
        <span>${issueData.status}</span>
      </div>
    </div>

    <div class="overview">
      <strong>Test Plan Overview</strong><br>
      <div class="section-summary"><strong>Total Test Cases:</strong> ${this.countTestCases(testPlan)}</div>
      <div class="section-summary"><strong>Generated:</strong> ${new Date(testPlan.generatedAt).toLocaleString()}</div>
      <div class="section-summary"><strong>Model:</strong> GROQ (openai/gpt-oss-120b)</div>
    </div>

    ${testCasesHtml}
    ${metadataHtml}

    <div class="footer">
      <p>This test plan was automatically generated by JIRA Test Plan Generator</p>
      <p>Generated on: ${new Date().toLocaleString()}</p>
    </div>
  </div>
</body>
</html>
    `;
  }

  /**
   * Generate test cases HTML
   */
  static generateTestCasesHtml(testPlan) {
    const sections = [
      { key: 'positiveScenarios', title: 'Positive Scenarios', icon: '✓' },
      { key: 'negativeScenarios', title: 'Negative Scenarios', icon: '✗' },
      { key: 'edgeCases', title: 'Edge Cases', icon: '⚡' },
      { key: 'securityTests', title: 'Security Tests', icon: '🔒' },
      { key: 'performanceTests', title: 'Performance Tests', icon: '⚙' },
    ];

    let html = '';

    for (const section of sections) {
      const testCases = testPlan.testPlan[section.key] || [];
      
      html += `<h2>${section.icon} ${section.title}</h2>`;
      
      for (const testCase of testCases) {
        const priorityClass = `priority-${(testCase.priority || 'medium').toLowerCase()}`;
        
        html += `
        <div class="test-case">
          <div class="test-case-header">${testCase.id}: ${testCase.title}</div>
          <div class="test-case-field">
            <span class="test-case-label">Description:</span>
            ${testCase.description}
          </div>
        `;

        if (testCase.steps && Array.isArray(testCase.steps)) {
          html += `
          <div class="test-case-field">
            <span class="test-case-label">Steps:</span>
            <ol class="steps-list">
          `;
          for (const step of testCase.steps) {
            html += `<li>${step}</li>`;
          }
          html += `
            </ol>
          </div>
          `;
        }

        html += `
          <div class="test-case-field">
            <span class="test-case-label">Expected Result:</span>
            ${testCase.expectedResult}
          </div>
        `;

        if (testCase.priority) {
          html += `
          <div class="test-case-field">
            <span class="test-case-label">Priority:</span>
            <span class="priority ${priorityClass}">${testCase.priority}</span>
          </div>
          `;
        }

        html += `</div>`;
      }
    }

    return html;
  }

  /**
   * Generate metadata HTML
   */
  static generateMetadataHtml(testPlan) {
    if (!testPlan.metadata) return '';

    let html = '<h2>Metadata & Analysis</h2>';

    if (testPlan.metadata.riskAreas && testPlan.metadata.riskAreas.length > 0) {
      html += '<h3>High-Risk Areas</h3><ul>';
      for (const area of testPlan.metadata.riskAreas) {
        html += `<li>${area}</li>`;
      }
      html += '</ul>';
    }

    if (testPlan.metadata.assumptions && testPlan.metadata.assumptions.length > 0) {
      html += '<h3>Assumptions</h3><ul>';
      for (const assumption of testPlan.metadata.assumptions) {
        html += `<li>${assumption}</li>`;
      }
      html += '</ul>';
    }

    return html;
  }

  /**
   * Download file helper
   */
  static downloadFile(content, filename, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Count test cases
   */
  static countTestCases(testPlan) {
    let count = 0;
    const sections = [
      'positiveScenarios',
      'negativeScenarios',
      'edgeCases',
      'securityTests',
      'performanceTests',
    ];

    for (const section of sections) {
      if (testPlan.testPlan[section]) {
        count += testPlan.testPlan[section].length;
      }
    }

    return count;
  }

  /**
   * Copy to clipboard helper
   */
  static async copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (error) {
      console.error('Failed to copy:', error);
      return false;
    }
  }
}

export { ExportUtils };
